# Generated by Django 5.2.6 on 2025-12-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherVlieland',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('wind_speed', models.FloatField(blank=True, null=True)),
                ('wind_gusts', models.FloatField(blank=True, null=True)),
                ('sea_temperature', models.FloatField(blank=True, null=True)),
                ('rain_chance', models.FloatField(blank=True, null=True)),
                ('weather_warnings', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Weather Vlieland',
                'verbose_name_plural': 'Weather Vlieland',
                'db_table': 'weatherVlieland',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
