# Generated by Django 5.2.6 on 2025-12-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_weathervlieland'),
    ]

    operations = [
        migrations.AddField(
            model_name='weathervlieland',
            name='wind_direction',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
