# Generated by Django 5.2.6 on 2025-12-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_weathervlieland_wind_direction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weathervlieland',
            old_name='rain_chance',
            new_name='wave_height',
        ),
        migrations.AddField(
            model_name='weathervlieland',
            name='sight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='weathervlieland',
            name='verwachting',
            field=models.TextField(blank=True, default=''),
        ),
    ]
