# Generated by Django 5.2.6 on 2025-12-14 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_location_tides'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tides',
            options={'ordering': ['timestamp'], 'verbose_name': 'Tide', 'verbose_name_plural': 'Tides'},
        ),
        migrations.AddField(
            model_name='tides',
            name='timestamp',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='tides',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tides', to='core.location'),
        ),
        migrations.AlterField(
            model_name='tides',
            name='tide_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tides',
            name='waterheight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
